name: useful
version: 1.0.18
author: Tomas Kulich <tomas.kulich@vacuumapps.com>
description: common useful utilities
homepage: http://vacuumlabs.com
dependencies:
  collection: any
  logging: any
  quiver: any
dev_dependencies:
  unittest: any
