name: yoseful
author: Tomas Kulich <tomas.kulich@vacuumapps.com>
version: 1.0.1
homepage: http://vacuumlabs.com
description: common useful utilities
dependencies:
  range: '>=1.1.0 <2.0.0'
dev_dependencies:
  unittest: any
