name: useful
author: Tomas Kulich <tomas.kulich@vacuumapps.com>
version: 1.0.1
homepage: http://vacuumlabs.com
description: common useful utilities
dependencies:
<<<<<<< HEAD
  range:
    git: git@github.com:tomaskulich/dart-range.git
=======
  logging: any
  range: '>=1.1.0 <2.0.0'
>>>>>>> master
dev_dependencies:
  unittest: any
