name: useful
author: Tomas Kulich <tomas.kulich@vacuumapps.com>
version: 1.0.2
homepage: http://vacuumlabs.com
description: common useful utilities
dependencies:
  logging: any
  quiver: any
dev_dependencies:
  unittest: any
